version: '3.1'
services:
  mongo:
    restart: always
    image: mongo
    volumes:
      - ./data:/data/db
    
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

    ports:
      - 27017:27017

  backend:
    restart: always
    build:
      context: backend
    depends_on:
      - mongo
    ports: 
      - 8810:8810

  frontend:
    build:
      context: frontend
    ports:
      - 3000:3000
    depends_on:
      - backend